#!/bin/sh

#note: run cuda hello-world on a single node, using a GPU

#SBATCH --job-name=cuhello
#SBATCH --output=%A-cuhello.out
#SBATCH --ntasks=16
#SBATCH --constraint=P100

export OMPI_MCA_pml=ob1
export OMPI_MCA_btl=tcp,self

#require tcp over infiniband
export OMPI_MCA_btl_tcp_if_include ib0

./hello_cuda

#-------------------------------------------------------------
